### ISSUE TITLE
Linux Compilation

### ISSUE THREAD

**Issue by trevordblack** [wkjarosz/SamplinSafari#1]
On Linux, compilation requires the libraries and headers for Xcursor and Xinerama.
They can be installed on a gnome distro with:
`sudo apt install libxinerama-dev libxcursor-dev`

Later during linking, xi is required:
`sudo apt install libxi-dev`

Sorry for creating an entire issue. Hope it's of value.

**Comment by wkjarosz** [comment]
That's correct. You can also look at the .travis.yml file for what packages are needed to successfully compile on e.g. ubuntu.

Since there doesn't seen to be any action needed on this, I'm closing the issue.
